---
title: "Homework 2"
author: "Maya Sinha"
date: "2022-10-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(dplyr)
library(tidyverse)
library(tidymodels)
library(tidyr)
```

### Question 1

```{r message = FALSE}
setwd("/Users/mayasinha/Desktop/PSTAT 131/homework-2/data") 
getwd()
abalone_df <- read_csv("abalone.csv")
age <- abalone_df[,9]+1.5
abalone_df <- cbind(abalone_df, age)
names(abalone_df)[10] <- "age"
abalone_df %>% 
  ggplot(aes(x = age)) +
  geom_histogram(bins = 60) 
```

Age seems to have normal distribution with a slight right skewed nature.

### Question 2

```{r}
set.seed(1215)

abalone_split <- initial_split(abalone_df, prop = .75, strata = age)
abalone_train <- training(abalone_split)
abalone_test <- testing(abalone_split)
```

### Question 3

```{r}
abalone_recipe <- recipe(age ~ type + longest_shell + diameter + height +	whole_weight + shucked_weight + viscera_weight	+ shell_weight, data = abalone_train) %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_interact(terms = ~ starts_with(type):shucked_weight + longest_shell:diameter + shucked_weight:shell_weight) %>% 
  step_center(all_predictors()) %>% 
  step_scale(all_predictors())

abalone_recipe
```
We do not use rings to predict age because age is directly based on rings. Age is equal to 1.5 plus the value of rings, hence we cannot use rings to predict age because the information is the same. 


### Question 4

```{r}
lm_model <- linear_reg() %>% 
  set_engine("lm")

lm_model
```

### Question 5

```{r}
lm_wflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(abalone_recipe)

lm_wflow
```

### Question 6

```{r}
abalone_fit <- fit(lm_wflow, abalone_train)
abalone_fit %>% extract_fit_parsnip() %>% tidy()

abalone_fit

new_abalone <- tibble(type = "F", longest_shell = 0.50, diameter = 0.1, height = 0.3, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1, rings = 0)
predict(abalone_fit, new_data = new_abalone)
```

### Question 7

```{r, include = FALSE}
library(yardstick)
```
```{r  message = FALSE}
abalone_train_res <- predict(abalone_fit, new_data = abalone_train %>% select(-age))
abalone_train_res <- bind_cols(abalone_train_res, abalone_train %>% select(age))


abalone_metrics <- metric_set(rmse, rsq, mae)
abalone_metrics(abalone_train_res, truth = age, 
                estimate = .pred)
```

interpret